steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/k8s-stackdriver/fluentd-gcp:$SHORT_SHA', './fluentd-gcp-image']
images:
- 'asia.gcr.io/$PROJECT_ID/k8s-stackdriver/fluentd-gcp:$SHORT_SHA'
